pipeline {
  agent any
  stages {
    stage('Initialize') {
      steps {
        script {
          name = "P.Anh 1"
          def lib = library('helperlibdev').helpers
          helper = lib.UnitTestReportHepler.new()
        }

        node(label: 'ssh') {
          script {
            wremote = ["host": "192.168.1.77", "allowAnyHosts": true]
          }

          sshCommand(remote: wremote, command: 'echo 123')
          sshCommand remote: ["host": "192.168.1.77", "allowAnyHosts": true], command: "echo 1"
        }

      }
    }

    stage('Works') {
      parallel {
        stage('Hello') {
          steps {
            echo "Hello ${name}"
          }
        }

        stage('Call helper lib') {
          steps {
            script {
              name = "atr"
            }

            echo "Hello ${name}"
            script {
              def remote = ["host": "192.168.1.77", "allowAnyHosts": true]
              withCredentials([sshUserPrivateKey(credentialsId: 'build-server-window', keyFileVariable: 'identity', passphraseVariable: '', usernameVariable: 'userName')]) {
                remote.user = userName
                remote.name = userName
                remote.identityFile = identity

                sshCommand remote: remote, command: "echo 1"
              }

              withCredentials([sshUserPrivateKey(credentialsId: 'build-server-window', keyFileVariable: 'identity', passphraseVariable: '', usernameVariable: 'userName')]) {
                remote.user = userName
                remote.name = userName
                remote.identityFile = identity

                sshCommand remote: remote, command: "echo 1"
              }
              echo 'Do something'
              echo 'Do something'
              echo 'Do something'

              println "ParseInt: ${helper.tryParseInt('123')}"
            }

          }
        }

      }
    }

  }
  environment {
    var1 = 'a1'
  }
}
